export default {
    "title": "Pick Any 5 Items",
    "discountPrice": "19.99",
    "items": [
        "1lb Bacon",
        "1.75lb Andy Sausage",
        "4lb Fresh Neck Bones",
        "2lb Ground Sausage",
        "4lb Chicken Leg qtr",
        "3lb Chicken Drums",
        "3lb Turkey Necks",
        "3lb Pig Feet",
        "3lb Chicken Gizzards",
        "1.5lb Chicken Wings",
        "3lb Rib Tips",
        "1.5lb Chicken Breast B/S",
        "2lb End Cut Pork Chops",
        "1 Whole Chicken",
        "2lb Smoked Neck Bones",
        "1lb Frozen Blue Crab",
        "1.5lb Ground Beef",
        "3lb Turkey Wings",
        "2lb PKG Hot Dogs",
        "1lb Tilapia Filet",
        "2lb Country Style Ribs",
        "2lb Pork Steak",
        "2lb Beef Livers",
        "3lb Bag of Rice",
        "2lb Pack Red Hots",
        "1lb Clams",
        "1lb American Cheese",
        "1lb Mussels",
        "2.5lb French Fries",
        "21oz Sausage Patties",
        "1lb Stew Beef"
    ]
};

